# -*- coding: utf-8 -*-
"""training_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8h2R7NuWeseOiQxPJry1WqaUKN1vDqo
"""

!pip install ultralytics
from ultralytics import YOLO
import os

from google.colab import files

print("Please select the ZIP file from your computer to upload:")
uploaded = files.upload()

"""After uploading the zip file, we'll unzip it. If you uploaded multiple files, please specify the correct zip file name in the next cell."""

# Get the name of the uploaded zip file
# Assuming you uploaded only one zip file or want to process the first one
zip_file_name = list(uploaded.keys())[0]

# Create a directory to extract the files into
import os
extraction_path = 'extracted_dataset'
os.makedirs(extraction_path, exist_ok=True)

# Unzip the uploaded file
!unzip -q "{zip_file_name}" -d "{extraction_path}"

print(f"Successfully unzipped '{zip_file_name}' to '{extraction_path}'.")

"""Now that the files are unzipped, let's list the contents of the `extracted_dataset` directory to see what's inside and identify your dataset file (e.g., a `.csv` file)."""

!ls -R extracted_dataset

# Create a new data.yaml specifically for Colab
yaml_content = """
train: /content/extracted_dataset/train/images
val: /content/extracted_dataset/valid/images

nc: 1
names: ['ball']
"""

with open('/content/extracted_dataset/data.yaml', 'w') as f:
    f.write(yaml_content)

# Cell 3: Your Training Code
from ultralytics import YOLO

def train_cricket_ball_detector():
    model = YOLO('yolov8n.pt')

    results = model.train(
        data='/content/extracted_dataset/data.yaml',  # <--- UPDATED PATH
        epochs=100,
        imgsz=640,
        batch=16,
        device=0,
        project='/content/drive/My Drive/EdgeFleet_Project', # Saves directly to Drive
        name='cricket_ball_detector',
        patience=20,
        save=True,

        # ... (Keep the rest of your augmentation parameters here) ...
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        degrees=10,
        translate=0.1,
        scale=0.5,
        flipud=0.0,
        fliplr=0.5,
        mosaic=1.0,
    )
    return results

# Run it
train_cricket_ball_detector()

from google.colab import files

# Path to the best.pt file, make sure this path is correct
model_path = '/content/drive/My Drive/EdgeFleet_Project/cricket_ball_detector/weights/best.pt'

# Download the file
files.download(model_path)

print(f'Downloaded {model_path} to your local machine.')



